# Commands to start on workspace startup
tasks:
  - init: mvn install
    command: cp .env.example .env
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven
